FROM node:18

WORKDIR /app

# Copy root config and lockfiles
COPY package.json package-lock.json turbo.json .npmrc ./

# 👇 Workspaces bhi chahiye before install
COPY apps/ apps/
COPY packages/ packages/

# Install dependencies
RUN npm install --workspaces --legacy-peer-deps

# Full copy (for turbo cache)
COPY . .

# Build only ws-server
RUN npx turbo run build --filter=ws-server...

# Change working directory
WORKDIR /app/apps/ws-server

EXPOSE 8080

CMD ["npm", "run", "dev"]