FROM node:20-alpine

WORKDIR /app

# Copy root files
COPY . .

# 👇 Workspaces chahiye
COPY apps/ apps/
COPY packages/ packages/

# Install dependencies
RUN npm install --workspaces --legacy-peer-deps

# Build only matching-engine
RUN npx turbo run build --filter=engine...

WORKDIR /app/apps/engine

CMD ["npm", "run", "dev"]